#!/usr/bin/env python3
"""Convert `data/e2jnotes.txt` (Anki TSV export) into `data/e2jNotes.js`.

The source is a tab-separated export with four columns per row:
    english, vocab, japanese, notes

CSV-style quoting (e.g. `"...""quoted""..."`) is honored so embedded quotes
in the notes column round-trip correctly.

Run from project root:
    python3 scripts/generate_e2j_notes.py
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "e2jnotes.txt"
OUT = ROOT / "data" / "e2jNotes.js"


def main():
    rows = []
    with SRC.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="\t", quotechar='"')
        for i, raw in enumerate(reader, start=1):
            cells = (raw + ["", "", "", ""])[:4]
            english, vocab, japanese, notes = (c.strip() for c in cells)
            if not english and not japanese:
                continue
            rows.append([i, english, vocab, japanese, notes])

    lines = ["// Generated by scripts/generate_e2j_notes.py — do not hand-edit.",
             "// Source: data/e2jnotes.txt (Anki TSV export).",
             "// Each entry: [id, english, vocab, japanese, notes]",
             "const e2jNotes = ["]
    for r in rows:
        encoded = ", ".join(json.dumps(c, ensure_ascii=False) for c in r)
        lines.append(f"  [{encoded}],")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(rows)} entries.")


if __name__ == "__main__":
    main()
