#!/usr/bin/env python3
"""Generate `service-worker.js` with a fresh precache list.

Walks the project for static assets (HTML, JS, audio, manifest, icon),
hashes their contents to derive a cache version, and writes
`service-worker.js` with the precache list and version baked in.

Re-run this any time you add or change cached files. A different hash means
the deployed SW installs into a new cache and old caches are purged.

Run from project root:
    python3 scripts/generate_service_worker.py
"""

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SW_FILE = ROOT / "service-worker.js"

ROOT_FILES = ["index.html", "manifest.webmanifest", "icon.svg"]
ASSET_DIRS = ["js", "data", "audio"]
ASSET_EXTS = {".html", ".js", ".mp3", ".webmanifest", ".json", ".svg"}


def collect():
    paths = []
    for name in ROOT_FILES:
        p = ROOT / name
        if p.exists():
            paths.append(p)
    for d in ASSET_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if p.is_file() and p.suffix in ASSET_EXTS:
                paths.append(p)
    return paths


def version_of(paths):
    h = hashlib.sha256()
    for p in sorted(paths):
        h.update(p.relative_to(ROOT).as_posix().encode())
        h.update(b"\0")
        h.update(p.read_bytes())
    return h.hexdigest()[:12]


def main():
    paths = collect()
    urls = ["./"] + [p.relative_to(ROOT).as_posix() for p in paths]
    version = version_of(paths)
    listing = ",\n  ".join(json.dumps(u) for u in urls)

    sw = f"""// Generated by scripts/generate_service_worker.py — do not hand-edit.
const CACHE_NAME = 'n4-study-{version}';
const PRECACHE_URLS = [
  {listing}
];

self.addEventListener('install', (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (event) => {{
  if (event.request.method !== 'GET') return;

  if (event.request.mode === 'navigate') {{
    event.respondWith(
      caches.match('./').then((cached) => cached || fetch(event.request))
    );
    return;
  }}

  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request))
  );
}});
"""
    SW_FILE.write_text(sw)
    print(f"Wrote {SW_FILE.name}: {len(urls)} entries, version {version}.")


if __name__ == "__main__":
    main()
