#!/usr/bin/env python3
"""Pre-generate Edge TTS audio for the Listening Practice sentences.

Reads `data/sentences.js`, synthesizes one MP3 per unique Japanese phrase to
`audio/sentences/`, and writes the manifest at `data/sentencesAudioManifest.js`.

Audio is only generated for actual *listening* exercises. Recall, vocab, and
E→J production decks intentionally don't get audio.

Existing MP3s are preserved (idempotent rerun).

Run from project root:
    scripts/.venv/bin/python scripts/generate_app_audio.py
"""

import asyncio
import hashlib
import json
import re
import sys
from pathlib import Path

import edge_tts

VOICE = "ja-JP-NanamiNeural"
ROOT = Path(__file__).resolve().parent.parent
CONCURRENCY = 8


SSTR = r"'((?:[^'\\]|\\.)*)'"   # single-quoted string with backslash escapes


def _unescape(s: str) -> str:
    return (s.replace('\\\\', '\x00')
             .replace('\\"', '"')
             .replace("\\'", "'")
             .replace('\\n', '\n')
             .replace('\\t', '\t')
             .replace('\x00', '\\'))


def extract_jp_field(src: str) -> list[str]:
    """`{jp: '...'}` form (sentences.js)."""
    return [_unescape(m) for m in re.findall(r"jp:\s*" + SSTR, src)]


SECTIONS = [
    {
        "name": "sentences",
        "src": "data/sentences.js",
        "extract": extract_jp_field,
        "out_dir": "audio/sentences",
        "manifest_file": "data/sentencesAudioManifest.js",
        "manifest_var": "sentencesAudioManifest",
    },
]


async def synth(text: str, out: Path, sem: asyncio.Semaphore) -> bool:
    async with sem:
        try:
            await edge_tts.Communicate(text, VOICE).save(str(out))
            return True
        except Exception as exc:
            print(f"  ! failed {text!r}: {exc}", file=sys.stderr)
            if out.exists():
                out.unlink()
            return False


async def run_section(section: dict, sem: asyncio.Semaphore) -> None:
    src_path = ROOT / section["src"]
    out_dir = ROOT / section["out_dir"]
    manifest_path = ROOT / section["manifest_file"]

    out_dir.mkdir(parents=True, exist_ok=True)
    src = src_path.read_text(encoding="utf-8")
    texts = sorted(set(section["extract"](src)))
    print(f"[{section['name']}] {len(texts)} unique phrases")

    manifest: dict[str, str] = {}
    new_tasks = []
    for text in texts:
        digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]
        fname = f"{digest}.mp3"
        manifest[text] = fname
        out = out_dir / fname
        if out.exists() and out.stat().st_size > 0:
            continue
        new_tasks.append(synth(text, out, sem))

    if new_tasks:
        results = await asyncio.gather(*new_tasks)
        new_count = sum(1 for r in results if r)
        # Drop entries whose synth failed.
        for text in list(manifest):
            f = out_dir / manifest[text]
            if not f.exists() or f.stat().st_size == 0:
                manifest.pop(text, None)
    else:
        new_count = 0

    body = (
        f"// Generated by scripts/generate_app_audio.py — do not hand-edit.\n"
        f"const {section['manifest_var']} = "
        + json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n"
    )
    manifest_path.write_text(body, encoding="utf-8")
    print(f"[{section['name']}] wrote {len(manifest)} manifest entries ({new_count} new MP3s)")


async def main() -> None:
    sem = asyncio.Semaphore(CONCURRENCY)
    for section in SECTIONS:
        await run_section(section, sem)
    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
