#!/usr/bin/env python3
"""Pre-generate Edge TTS audio for the conversation practice questions.

Reads `data/conversations.js`, extracts the Japanese question from each row
(`[id, question_jp, answer_en, answer_jp]`), and synthesizes an MP3 per
unique question using Microsoft Edge's neural Japanese voice. Writes files
to `audio/conversations/<hash>.mp3` and a JS manifest at
`data/conversationAudioManifest.js` mapping question -> filename.

Run:
    scripts/.venv/bin/python scripts/generate_conversation_audio.py
"""

import asyncio
import hashlib
import json
import re
import sys
from pathlib import Path

import edge_tts

VOICE = "ja-JP-NanamiNeural"
ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "data" / "conversations.js"
OUT_DIR = ROOT / "audio" / "conversations"
MANIFEST_FILE = ROOT / "data" / "conversationAudioManifest.js"

ROW_RE = re.compile(
    r'\[\s*\d+\s*,\s*"((?:[^"\\]|\\.)*)"'
)


def extract_jp_texts(source: str) -> list[str]:
    return sorted({m.group(1) for m in ROW_RE.finditer(source)})


async def synth(text: str, out: Path) -> None:
    await edge_tts.Communicate(text, VOICE).save(str(out))


async def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    src = DATA_FILE.read_text(encoding="utf-8")
    texts = extract_jp_texts(src)
    print(f"Found {len(texts)} unique JP phrases in {DATA_FILE.name}")

    manifest: dict[str, str] = {}
    new_count = 0
    for text in texts:
        digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]
        fname = f"{digest}.mp3"
        manifest[text] = fname
        out = OUT_DIR / fname
        if out.exists() and out.stat().st_size > 0:
            continue
        try:
            await synth(text, out)
            new_count += 1
            print(f"  + {text}  ->  {fname}")
        except Exception as exc:
            print(f"  ! failed {text!r}: {exc}", file=sys.stderr)
            manifest.pop(text, None)

    body = (
        "// Generated by scripts/generate_conversation_audio.py — do not hand-edit.\n"
        "const conversationAudioManifest = "
        + json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n"
    )
    MANIFEST_FILE.write_text(body, encoding="utf-8")
    print(
        f"Wrote {len(manifest)} entries to {MANIFEST_FILE.name} "
        f"({new_count} new MP3s)"
    )


if __name__ == "__main__":
    asyncio.run(main())
